### ISSUE TITLE
Crash when selecting too big images

### ISSUE THREAD

**Issue by nooone** [cobolfoo/gdx-skineditor#12]
The following crash happens when I select an image to create a NinePatch that is bigger than 1024px in width.

```
Exception in thread "LWJGL Application" java.lang.RuntimeException: Error packing files.
        at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:625)
        at org.shadebob.skineditor.NinePatchEditorDialog.refreshPreview(NinePatchEditorDialog.java:373)
        at org.shadebob.skineditor.NinePatchEditorDialog$1.changed(NinePatchEditorDialog.java:136)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:166)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:131)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:112)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:86)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:272)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:305)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:199)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
Caused by: java.lang.Exception: Error processing directory: C:\Users\n0_0ne\AppData\Local\Temp\skin_ninepatch
        at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:157)
        at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.process(TexturePackerFileProcessor.java:145)
        at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:121)
        at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.process(TexturePackerFileProcessor.java:99)
        at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:623)
        ... 13 more
Caused by: java.lang.RuntimeException: Image does not fit with max page width 1024 and paddingX 2: button[0,0 1075x484]
        at com.badlogic.gdx.tools.texturepacker.MaxRectsPacker.packPage(MaxRectsPacker.java:103)
        at com.badlogic.gdx.tools.texturepacker.MaxRectsPacker.pack(MaxRectsPacker.java:75)
        at com.badlogic.gdx.tools.texturepacker.TexturePacker.pack(TexturePacker.java:102)
        at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.processDir(TexturePackerFileProcessor.java:220)
        at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:155)
        ... 17 more

```

**Comment by cobolfoo** [comment]
I think you should keep big images such as 1024x1024 outside of your skin. You want to use it as an actor background ?
