### ISSUE TITLE
Freeze when select "Import Image"

### ISSUE THREAD

**Issue by dawadam** [cobolfoo/gdx-skineditor#16]
Hi,
Screen freeze when click on "Import Image" or other button for file selector.
Regards.

> Exception in thread "LWJGL Application" java.lang.UnsupportedOperationException: TRANSLUCENT translucency is not supported.
>	at java.awt.Window.setOpacity(Window.java:3598)
>	at java.awt.Frame.setOpacity(Frame.java:962)
>	at org.shadebob.skineditor.DrawablePickerDialog$2.changed(DrawablePickerDialog.java:108)
>	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
>	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:166)
>	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:131)
>	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:112)
>	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:86)
>	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
>	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
>	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:272)
>	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:305)
>	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:199)
>	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)

**Comment by gunmetal313** [comment]
Try my fork :) https://github.com/gunmetal313/gdx-skineditor/releases

**Comment by dawadam** [comment]
Thanks

**Comment by lcjury** [comment]
I have the same problem with @gunmetal313 fork :(
